const Router = require('express').Router()
const UserRouter = require('./UserRouter')
const PostRouter = require('./PostRouter')
const CommentRouter = require('./CommentRouter')
const CardRouter = require('./CardRouter')
Router.use('/users', UserRouter)
Router.use('/feed', PostRouter)
Router.use('/comment', CommentRouter)
Router.use('/card', CardRouter)
module.exports = Router
